### ISSUE TITLE
勾上发现音乐页的看看后 没效果

### ISSUE THREAD

**Issue by Marce1ek** [miku3333/miku-plugin#1]
麻烦大佬看下🥺
![QQ截图20221121061746](https://user-images.githubusercontent.com/99329516/202929300-04ac6cca-f7fd-426f-98a5-2ad2a5821fa9.jpg)
![QQ截图20221121061757](https://user-images.githubusercontent.com/99329516/202929308-0a2ee416-0646-413f-a1f3-12401b86d209.jpg)

**Comment by miku3333** [comment]
暂时

**Comment by miku3333** [comment]
后续会修, 暂时可以在自定义配置里输一行这个就好了
[data-nej-selector*=__nLive]/看看
![F2AED58129E6D4FFE35013E1AED45B3B](https://user-images.githubusercontent.com/67085471/202963264-286bd179-ec15-42ad-82b7-feeca9f26346.png)

**Comment by Marce1ek** [comment]
加上之后可以了 谢谢老哥

**Comment by miku3333** [comment]
更新至0.1.1后已修复看看不生效问题
