### ISSUE TITLE
考虑给侧边栏插件管理加个图标吗？

### ISSUE THREAD

**Issue by Kaenagi** [miku3333/miku-plugin#10]
使用StyleSnippet侧边栏图标之后
![image](https://user-images.githubusercontent.com/104701550/216749534-272ae74e-655e-4fa6-a0cc-9c6338ec82db.png)

**Comment by miku3333** [comment]
更新至0.1.2后添加了图标, 且可通过网易云图标打开的插件管理面板关闭侧边栏的插件管理入口#7
