### ISSUE TITLE
插件本身隐藏功能

### ISSUE THREAD

**Issue by picsky** [miku3333/miku-plugin#3]
提一个建议：
后期是否可以考虑加入`插件管理`按钮侧边栏隐藏功能，集成到设置之类的。
在删除掉大量我不使用的功能后，我发现侧边栏的插件管理按钮都多余了，所以产生这样一个需求。
极简到底嘛！感谢作者开发的这么好用的插件。

**Comment by miku3333** [comment]
#4 
无法完全删除插件管理, 删除插件管理后想要再次打开需要按f12清空本地缓存
更新至0.1.1后可选择暂时隐藏插件管理, 鼠标移入侧边栏时会显示插件管理
