### ISSUE TITLE
按钮跳动

### ISSUE THREAD

**Issue by fishdown** [miku3333/miku-plugin#7]
鼠标在侧边栏和主页面移动的时候 
https://user-images.githubusercontent.com/119657362/215509845-b2101037-2825-4e93-a4bb-5673370a5476.mp4

**Comment by miku3333** [comment]
请关闭屏蔽中的最后一项插件管理

**Comment by fishdown** [comment]
佬，我没表达清楚，我又录了一下，你重新看一下这个视频，

https://user-images.githubusercontent.com/119657362/216758924-e9fbc6fd-4c0f-49ed-98fb-cb6e286deb68.mp4

**Comment by miku3333** [comment]
0.1.2版本在网易云图标打开的插件管理中点击一下那行文字即可完全关闭, 等会发布后可以更新一下
![image](https://user-images.githubusercontent.com/67085471/216762900-0f346e05-ecbf-42af-be4e-0486f6e4e5ea.png)

**Comment by miku3333** [comment]
已更新至0.1.2

**Comment by fishdown** [comment]
效果很好，感谢大佬，幸苦了
