### ISSUE TITLE
一个小小的建议——能不能增加一个选项把插件管理放到BetterNCM界面

### ISSUE THREAD

**Issue by AdoShan** [miku3333/miku-plugin#9]
在初步设置阶段将插件的设置选项放在侧边栏确实方便设置以实现自己不想要的组件，但是一旦设置完成大概率是不会再去设置的，所以后期并不是非常高频率地对插件进行设置，可以考虑增加一个选项把插件设置从侧边栏移动到BetterNCM界面，参考绝大多数插件。
![image](https://user-images.githubusercontent.com/44154107/216525476-a72243dd-e913-4896-aa02-e68106ea1247.png)

**Comment by miku3333** [comment]
更新至0.1.2后可通过网易云图标打开的插件管理面板关闭侧边栏的插件管理入口 #7
